name: flutter_cielo
description: Pacote para criar pagamentos usando o SDK da Cielo e-Commerce. Para mais informações acesse a documentação oficial da Cielo e-Commerce para desenvolvedores.
version: 1.0.6
author: Jacob Moura <jacobaraujo7@gmail.com>
homepage: https://github.com/jacobaraujo7/flutter-cielo

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  #json_annotation: ^2.0.0
  dio: ^3.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
